pgroonga/pgroonga

src/pgrn-groonga.c

When Groonga version is "10.0.0", `strcmp(libgroonga_version, "8.0.2")` returns `-7`.
This return value unexpected.
Therefore, I've fixed a process to compare the version.

Fix a process of compare the version

---

packages/postgresql-10-pgroonga/yum/centos-6/Dockerfile
packages/postgresql-10-pgroonga/yum/centos-7/Dockerfile
packages/postgresql-11-pgroonga/yum/centos-6/Dockerfile
packages/postgresql-11-pgroonga/yum/centos-7/Dockerfile
packages/postgresql-12-pgroonga/yum/centos-6/Dockerfile
packages/postgresql-12-pgroonga/yum/centos-7/Dockerfile
packages/postgresql-12-pgroonga/yum/centos-8/Dockerfile
packages/postgresql-9.5-pgroonga/yum/centos-6/Dockerfile
packages/postgresql-9.5-pgroonga/yum/centos-7/Dockerfile
packages/postgresql-9.6-pgroonga/yum/centos-6/Dockerfile
packages/postgresql-9.6-pgroonga/yum/centos-7/Dockerfile

This fix is only temporary.
This bug is fixing upstream now.

package centos: fix a parse error for pgdg-redhat-all.repo

---

.github/workflows/linux.yml

Because PostgreSQL13 is installed in Ubuntu 20.04 on GitHub Actions.
TODO:
This PR is testing now.
https://github.com/komainu8/pgroonga/actions/runs/309741633

ci linux: update version to remove.

---

expected/function/wal-truncate/many-records.out
sql/function/wal-truncate/many-records.sql
src/pgrn-wal.c

GitHub: fix #150 Reported by BiscuitsColonel Thanks!!!
PostgreSQL occurs PANIC if we truncate PGroonga's WAL that it includes many modifications.
Because the number of Locks that we require for truncating WAL is limited.
The maximum number of these locks is 200.
See:
https://github.com/postgres/postgres/blob/REL_13_1/src/backend/storage/lmgr/lwlock.c#L208
The loop of PGrnWALTruncate() may very well run more than 200 times.
So, we release locks every GenericXLogFinish().

wal: release a lock every time that a page in a block is initialized

---

.github/workflows/linux.yml

This could have caught #203 if it had been in place before Thursday’s PostgreSQL releases.

ci linux: Test against PostgreSQL snapshot builds

---

.github/workflows/linux.yml

Apparently APT accepted these, but that’s not documented so we shouldn’t rely on it.

ci linux: Remove accidental quotes

---

.github/workflows/linux.yml
.github/workflows/windows.yml
packages/apt/test.sh
packages/yum/test.sh

Because PostgreSQL 14.3, 13.7, 12.11, 11.16, and 10.21 have been already released.

ci: enable tests that have failed temporarily due to PostgreSQL's bug

---

.github/workflows/linux.yml

Because PostgreSQL 15 depends postgresql-common (>= 241~).
However, the version of postgresql-common on Ubuntu 20.04 is 214ubuntu0.1.

ci: use ubuntu-22.10 only when we execute tests for PostgreSQL 15

---

packages/postgresql-13-pgroonga/yum/amazon-linux-2/Dockerfile
packages/yum/postgresql-pgroonga.spec.in
packages/yum/test.sh

`pg_config` is provided by `postgresql-private-devel` only for PostgreSQL 13 on Amazon Linux 2.
`pg_config` is provided by `libpq-devel` for others.
So `libpq-devel` isn't needed only for PostgreSQL 13 on Amazon Linux 2.

ci: don't use libpq-devel for PostgreSQL 13 on Amazon Linux 2

---

.github/workflows/package.yml
packages/postgresql-10-pgdg-pgroonga/Rakefile
packages/postgresql-10-pgdg-pgroonga/apt/ubuntu-jammy-arm64/from
packages/postgresql-10-pgdg-pgroonga/apt/ubuntu-jammy/Dockerfile
packages/postgresql-11-pgdg-pgroonga/Rakefile
packages/postgresql-11-pgdg-pgroonga/apt/ubuntu-jammy-arm64/from
packages/postgresql-11-pgdg-pgroonga/apt/ubuntu-jammy/Dockerfile
packages/postgresql-12-pgdg-pgroonga/Rakefile
packages/postgresql-12-pgdg-pgroonga/apt/ubuntu-jammy-arm64/from
packages/postgresql-12-pgdg-pgroonga/apt/ubuntu-jammy/Dockerfile
packages/postgresql-13-pgdg-pgroonga/Rakefile
packages/postgresql-13-pgdg-pgroonga/apt/ubuntu-jammy-arm64/from
packages/postgresql-13-pgdg-pgroonga/apt/ubuntu-jammy/Dockerfile
packages/postgresql-14-pgdg-pgroonga/Rakefile

I support PostgreSQL 10 - 14 PGDG packages on Ubuntu 22.04.
GitHub #228.
Reported by sousuke0422. Thanks!!!

packages: add support for Ubuntu 22.04 (Jammy Jellyfish) with PostgreSQL PGDG package

---

src/pgrn-compatible.h
src/pgrn-wal.c

Because RELKIND_HAS_PARTITIONS is added since PostgreSQL 15.
See: https://github.com/postgres/postgres/commit/37b2764593c073ca61c2baebd7d85666e553928b

Use RELKIND_HAS_PARTITIONS only PostgreSQL 15 or later

---

tools/download-rpm.sh

Because gflags and glog are not downloaded when we use this tool in AlmaLinux 8.

tools: enable powertools repository for AlmaLinux 8

---

tools/download-rpm.sh

We can download RPM for groonga-plugin-suggest and groonga if we use "USE_GROONGA_PLUGIN_SUGGEST=yes" and "USE_GROONGA_BIN=yes" as below.
```bash
USE_GROONGA_PLUGIN_SUGGEST=yes \
USE_GROONGA_BIN=yes \
/pgroonga/tools/download-rpm.sh \
${PGROONGA_VERSION} \
${GROONGA_VERSION} \
${POSTGRESQL_VERSION}
```

tools/download-rpm: add download targets

---

.github/workflows/windows.yml

Because PostgreSQL 16.2, 15.6, 14.11, 13.14, and 12.18 released at 2024-02-08.

ci windows: use the latest versions

---

.github/workflows/macos.yml

Because if Groonga which Homebrew provide is older than Groonga which PGroonga require, PGroonga install fail.

ci macos: update Homebrew if Groonga which Homebrew provide is older than Groonga which PGroonga require

---

src/pgroonga.c
test/test-sequential-scan.rb

This is happen when the following conditions are satisfied:
* In transaction
* `(nExecutions % vacuumFrequency) == 0`
* https://github.com/pgroonga/pgroonga/blob/c9804ab4801ff0e77cf38775063a933425cb2150/src/pgrn-sequential-search.c#L157
In this case, `PGrnBeforeShmemExit()` is executed before `PGrnReleaseSequentialSearch()`. And `PGrnReleaseSequentialSearch()` touches a Groonga object. But `grn_fin()` is called in `PGrnBeforeShmemExit()`. So touching a Groonga object crashes the process.
We don't need to run `PGrnReleaseSequentialSearch()` because all resources are released in `PGrnBeforeShmemExit()`. So we can unregister all resource release callbacks.

Fix a crash on connection close

---

data/pgroonga--3.2.0--3.2.1.sql
data/pgroonga.sql
expected/function/list-broken-indexes/multiple.out
expected/function/list-broken-indexes/nothing.out
sql/function/list-broken-indexes/multiple.sql
src/pgrn-list-broken-indexes.c

Prepare to implement a function that lists the indexes of PGroonga's that may be broken. After this, add a process to filter only broken indexes.

list-broken-indexes: Returns a list of PGroonga indexes

---

.github/workflows/macos.yml

Because `macos-latest` (Image: macos-14-arm64) fails.

ci: Run macos test with `macos-12`

---

data/pgroonga--3.2.0--3.2.1.sql
data/pgroonga--3.2.1--3.2.0.sql
data/pgroonga.sql
src/pgrn-wal.c
test/test-streaming-replication.rb

Prepare to implement a function that returns a list of PGroonga indexes with unapplied WAL.

Add pgroonga_list_lagged_indexes() skeleton

---

src/pgroonga.c

If it failed, PGroonga crashes, so it is checked by PGrnCheck().
This commit does not add checks to all `grn_expr_append_op`.
It is split up because of the many targets.

Check with PGrnCheck() after `grn_expr_append_op` in pgroonga.c

---

src/pgroonga.c

This commit does not replace all grn_expr_append_op().
It is split up because of the many targets.

Use PGrnExprAppendOp() instead of grn_expr_append_op() in pgroonga.c

---

data/pgroonga--3.2.0--3.2.1.sql
data/pgroonga--3.2.1--3.2.0.sql
data/pgroonga.sql
expected/term-search/text/equal-condition/row-level-security/bitmapscan.out
expected/term-search/text/equal-condition/row-level-security/indexscan.out
expected/term-search/text/equal-condition/row-level-security/seqscan.out
src/pgrn-condition.c
src/pgrn-condition.h

Make Groonga's `fuzzy_max_distance_ratio` can be used in pgroonga_condition().
https://groonga.org/docs/reference/commands/select.html#typo-tolerance
This commit just implements the passing of `fuzzy_max_distance_ratio`.
Implementation of search using `fuzzy_max_distance_ratio` will be a separate commit.

Add `fuzzy_max_distance_ratio` parameter to pgroonga_condition()

---

src/pgroonga-primary-maintainer.c
test/test-streaming-replication.rb

After this, the following features will be implemented.
* Check WAL size
* Run `REINDEX CONCURRENTLY`
* Routine run in pgroonga_primary_maintainer_main

pgroonga-primary-maintainer:  Register a background worker

---

expected/full-text-search/text/single/query-condition-v2/and/blank/bitmapscan.out
expected/full-text-search/text/single/query-condition-v2/and/blank/indexscan.out
expected/full-text-search/text/single/query-condition-v2/and/blank/seqscan.out
expected/full-text-search/text/single/query-v2/and/blank/bitmapscan.out
expected/full-text-search/text/single/query-v2/and/blank/indexscan.out
expected/full-text-search/text/single/query-v2/and/blank/seqscan.out
sql/full-text-search/text/single/query-condition-v2/and/blank/bitmapscan.sql
sql/full-text-search/text/single/query-condition-v2/and/blank/indexscan.sql
sql/full-text-search/text/single/query-condition-v2/and/blank/seqscan.sql
sql/full-text-search/text/single/query-v2/and/blank/bitmapscan.sql
sql/full-text-search/text/single/query-v2/and/blank/indexscan.sql
sql/full-text-search/text/single/query-v2/and/blank/seqscan.sql
src/pgrn-string.c
src/pgrn-string.h
src/pgroonga.c

An error will occur if any of the multiple conditions have a blank space condition.
This is because grn_expr_parse() in PGrnSearchBuildConditionQuery() doesn't add any condition but PGroonga adds logical AND later. Logical AND requires 2 conditions but there is only 1 condition in this case. So the expression becomes invalid.
If the condition contains only blank spaces, there should be no hits, so the result will be empty.

query-v2: Fix a crash bug with multiple conditions including blank only query condition

---

test/test-pgroonga-primary-maintainer.rb
test/test-streaming-replication.rb

Streaming replication is not required.
The test is not changed, just moved.

pgroonga-primary-maintainer: Separate test from test-streaming-replication

---

.github/workflows/package.yml

Because Groonga unvendor apache/arrow. We need to checkout apache/arrow manually to build .deb/.rpm packages.
ref: https://github.com/groonga/groonga/pull/1789

ci package: checkout Apache Arrow source

---

packages/pgroonga/yum/pgroonga.spec.in
packages/yum/postgresql-pgroonga.spec.in
pgroonga.mk
test/helpers/sandbox.rb
test/test-pgroonga-primary-maintainer.rb
tools/pgroonga-primary-maintainer.sh

This is only for a primary server. This should not be used for a standby server.
This is a shell script that checks the size of the WAL in `pgroonga_wal_status()` and runs `REINDEX INDEX CONCURRENTLY ` if it exceeds the threshold.
This should be executed periodically.

Add pgroonga-primary-maintainer.sh

---

tools/pgroonga-primary-maintainer.sh

thresholds ->
threshold
Because we specify only one.

pgroonga-primary-maintainer: Rename option name

---

tools/pgroonga-primary-maintainer.sh

Remove debug prints as it is used as a command line tool.

pgroonga-primary-maintainer: Remove `set -x`

---

test/test-pgroonga-primary-maintainer.rb
tools/pgroonga-primary-maintainer.sh

Unnecessary errors are displayed, so stderr also redirects to `/dev/null`.

pgroonga-primary-maintainer: Remove unnecessary output

---

test/test-pgroonga-primary-maintainer.rb

* Bug caused by overwriting `command` in the `which` method
* Usage content changes depending on the environment

test-pgroonga-primary-maintainer: Fix tests

---

test/helpers/sandbox.rb
test/test-pgroonga-primary-maintainer.rb

We use `which` in other tests, so we moved it to the helper.

Move `which` method to `Helpers::CommandRunnable` as `find_command` method

---

tools/systemd/pgroonga-generate-primary-maintainer-service.sh

Redirect stderr to /dev/null since some environments output stderr when the command is not found.

pgroonga-generate-primary-maintainer-service: Suppress unnecessary output

---

.github/workflows/macos.yml

GitHub: fix GH-522
`pgroonga-benchmark` gem couldn't run because of the following error. Because the `pg_ext.bundle` in `pg` gem is attempting to load the PostgreSQL 14 library (libpq.5.dylib), while PostgreSQL 15 is installed on the system.
```
pgroonga-benchmark is required: dlopen(/Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/pg-1.5.7/lib/pg_ext.bundle, 0x0009): Library not loaded: /opt/homebrew/opt/postgresql@14/lib/postgresql@14/libpq.5.dylib
Referenced from: <01D03C90-3C16-3457-B7D6-14AB32602E14> /Users/runner/work/pgroonga/pgroonga/vendor/bundle/ruby/3.3.0/gems/pg-1.5.7/lib/pg_ext.bundle
Reason: tried: '/opt/homebrew/opt/postgresql@14/lib/postgresql@14/libpq.5.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/postgresql@14/lib/postgre …
```

ci macos: update bundler cache in each PostgreSQL version

---

data/pgroonga--3.2.1--3.2.2.sql
packages/apt/test.sh
packages/yum/test.sh

If you upgrade to 3.2.1 with PGroonga already installed, you get the following error.
```
WHERE content &@~ pgroonga_condition('PGroonga');
^
HINT:  Could not choose a best candidate function. You might need to add explicit type casts.
```
The log also reports the following error.
```
ERROR:  function pgroonga_condition(unknown) is not unique at character 84
```
This is due to a bug in `data/pgroonga--3.2.0--3.2.1.sql` where two pgroonga_condition() were defined.
Therefore, the unnecessary pgroonga_condition() definition was removed.

Remove unnecessary pgroonga_condition() definitions

---

Rakefile

Related: ce13d7b3f30ed53b7e0e907c26c5ede47f702d37
It also had to be removed from the Rakefile.

package: Remove postgresql-13-pgroonga from Rakefile

---

tools/generate-metadata-for-modifyrepo.sh

When you download the RPM files with `tools/download-rpm.sh` and build a local repository, installing `groonga-tokenizer-mecab` will result in the following error.
```
No available modular metadata for modular package 'mecab-0.996-2.module_el8.6.0+3340+d764b636.x86_64', it cannot be installed on the system
No available modular metadata for modular package 'mecab-ipadic-2.7.0.20070801-16.module_el8.6.0+3340+d764b636.x86_64', it cannot be installed on the system
Error: No available modular metadata for modular package
```
This error occurs because there is no metadata for the modular repository.
Add a script to generate the YAML required when registering metadata with `modifyrepo_c` command.

tools: Add a script to generate YAML for use with `modifyrepo_c` command

---

tools/generate-metadata-for-modifyrepo.sh

It was not a simple file name.
Reference: https://github.com/fedora-modularity/libmodulemd/blob/2.15.0/yaml_specs/modulemd_stream_v2.yaml#L671-L674
```
RPM artifacts shipped with this module
A set of NEVRAs associated with this module. An epoch number in the
NEVRA string is mandatory.
```

tools/generate-metadata-for-modifyrepo: Set the artifact correctly

---

.github/workflows/windows.yml

PostgreSQL 16.4, 15.8, 14.13, 13.16, and 12.20 has been released at 2024-08-08. 
ref: https://www.postgresql.org/about/news/postgresql-164-158-1413-1316-1220-and-17-beta-3-released-2910/
Tests of Windows that I modified was successful as below.
https://github.com/pgroonga/pgroonga/actions/runs/10311559289

ci windows: use the latest version

---

packages/apt/test.sh
packages/test-primary-maintainer.sh
packages/test-systemd-timer.sh
packages/yum/test.sh

Also updated `test-systemd-timer.sh` as it is not stable on CI.
Changed timer enable/disable timing so that `REINDEX` is done after getting before status.
There were cases where `REINDEX` had already ended when the before status was fetched.

ci: Run primary-maintainer test

---

test/test-pgroonga-primary-maintainer.rb
test/test-query-expand.rb

`windows?` defined in `test/helpers/sandbox.rb`.
In the testing of this repository, we use `windows?`, so we will unify the use of it.

test: Use `windows?` instead of `Gem.win_platform?`

---

src/pgrn-variables.c
src/pgroonga.c
test/test-pgroonga-parameter.rb

This is a bug that occurs when `pgroonga.log_type = postgresql`.
The change in `log_level` was not reflected in the output.
For example, setting to `pgroonga.log_level = debug` did not output debug logs.

Fix bug that log_level is not reflected

---

src/pgrn-variables.c
test/test-pgroonga-parameter.rb

GitHub: fixes GH-532
PGroonga's logs are also rotated using Groonga's log rotation.
It is available in Groonga 14.0.7 or later because there is a bug in Groonga 14.0.6 or earlier.

Add `pgroonga.*log_rotate_threshold_size` parameter

---

src/pgrn-groonga.h
src/pgrn-variables.c

You can use the features by upgrading only Groonga without rebuilding PGroonga.

variables: logging settings: Check Groonga version at runtime, not at build time

---

.github/workflows/linux.yml

GitHub: GH-552
This is part of the task of supporting for PostgreSQL 17.
We're using unreleased PostgreSQL 17. This uses released PostgreSQL 17  instead of unreleased PostgreSQL 17.

ci linux: use released PostgreSQL 17

---

.github/workflows/package.yml
packages/postgresql-17-pgdg-pgroonga/Rakefile
packages/postgresql-17-pgdg-pgroonga/apt/ubuntu-jammy-arm64/from
packages/postgresql-17-pgdg-pgroonga/apt/ubuntu-jammy/Dockerfile

GitHub: GH-552
We add support for PostgreSQL 17 on Ubuntu jammy by this PR.

packages ubuntu jammy: add support for PostgreSQL 17

---

.github/workflows/package.yml
packages/postgresql-17-pgdg-pgroonga/Rakefile
packages/postgresql-17-pgdg-pgroonga/apt/ubuntu-noble-arm64/from
packages/postgresql-17-pgdg-pgroonga/apt/ubuntu-noble/Dockerfile

GitHub: GH-552
We add support for PostgreSQL 17 on Ubuntu noble by this PR.

packages ubuntu noble: add support for PostgreSQL 17

---

.github/workflows/macos.yml

GitHub: GH-552
We add support for PostgreSQL 17 on CI of macOS workflow by this PR.

ci macos: add support for PostgreSQL 17

---

.github/workflows/windows.yml

GitHub: GH-552
We use released PostgreSQL 17 not unreleased PostgreSQL 17 for Windows by this PR.

ci windows: add support for PostgreSQL 17

---

packages/postgresql-12-pgdg-pgroonga/apt/debian-bookworm-arm64/from
packages/postgresql-12-pgdg-pgroonga/apt/ubuntu-focal-arm64/from
packages/postgresql-12-pgdg-pgroonga/apt/ubuntu-jammy-arm64/from
packages/postgresql-12-pgdg-pgroonga/apt/ubuntu-noble-arm64/from
packages/postgresql-13-pgdg-pgroonga/apt/debian-bookworm-arm64/from
packages/postgresql-13-pgdg-pgroonga/apt/ubuntu-focal-arm64/from
packages/postgresql-13-pgdg-pgroonga/apt/ubuntu-jammy-arm64/from
packages/postgresql-13-pgdg-pgroonga/apt/ubuntu-noble-arm64/from
packages/postgresql-14-pgdg-pgroonga/apt/debian-bookworm-arm64/from
packages/postgresql-14-pgdg-pgroonga/apt/ubuntu-focal-arm64/from
packages/postgresql-14-pgdg-pgroonga/apt/ubuntu-jammy-arm64/from
packages/postgresql-14-pgdg-pgroonga/apt/ubuntu-noble-arm64/from
packages/postgresql-15-pgdg-pgroonga/apt/debian-bookworm-arm64/from
packages/postgresql-15-pgdg-pgroonga/apt/ubuntu-focal-arm64/from
packages/postgresql-15-pgdg-pgroonga/apt/ubuntu-jammy-arm64/from
packages/postgresql-15-pgdg-pgroonga/apt/ubuntu-noble-arm64/from
packages/postgresql-15-pgroonga/apt/debian-bookworm-arm64/from
packages/postgresql-16-pgdg-pgroonga/apt/debian-bookworm-arm64/from
packages/postgresql-16-pgdg-pgroonga/apt/ubuntu-focal-arm64/from
packages/postgresql-16-pgdg-pgroonga/apt/ubuntu-jammy-arm64/from
packages/postgresql-16-pgdg-pgroonga/apt/ubuntu-noble-arm64/from
packages/postgresql-17-pgdg-pgroonga/apt/debian-bookworm-arm64/from
packages/postgresql-17-pgdg-pgroonga/apt/ubuntu-focal-arm64/from
packages/postgresql-17-pgdg-pgroonga/apt/ubuntu-jammy-arm64/from
packages/postgresql-17-pgdg-pgroonga/apt/ubuntu-noble-arm64/from

Because of build failure.
Example of error:
```
ERROR: failed to solve: arm64v8/ubuntu:focal: failed to resolve source metadata for docker.io/arm64v8/ubuntu:focal: no match for platform in manifest: not found
```

packages apt: use --platform=linux/arm64 explicitly

---

.github/workflows/linux.yml
test/test-pgroonga-check.rb
test/test-pgroonga-crash-safer.rb

Time-expensive tests are skipped on CI, but this may delay noticing failures.
Change to run all tests once a day.
It usually takes about 2 hours, so we set a timeout of 150 minutes.

ci: Run all tests, on a periodic run by schedule

---

expected/regexp/text-array/regexp-v2/empty-string/seqscan.out
sql/regexp/text-array/regexp-v2/empty-string/seqscan.sql
src/pgroonga.c

We can't add tests for indexscan and bitmapscan. Because they reject an empty pattern for now.
But we'll accept it in a separated PR. We'll add tests for them in the PR.

regexp-v2: add a test for empty pattern with seqscan

---

expected/regexp/text-array/regexp-v2/null/bitmapscan.out
expected/regexp/text-array/regexp-v2/null/indexscan.out
expected/regexp/text-array/regexp-v2/null/seqscan.out
sql/regexp/text-array/regexp-v2/null/bitmapscan.sql
sql/regexp/text-array/regexp-v2/null/indexscan.sql
sql/regexp/text-array/regexp-v2/null/seqscan.sql

`&~(text[], text)` specifies `STRICT`.
So, `&~ NULL` always returns `NULL`.

regexp-v2 text[]: add tests for NULL pattern

---

expected/regexp/text/regexp-v2/null/bitmapscan.out
expected/regexp/text/regexp-v2/null/indexscan.out
expected/regexp/text/regexp-v2/null/seqscan.out
sql/regexp/text/regexp-v2/null/bitmapscan.sql
sql/regexp/text/regexp-v2/null/indexscan.sql
sql/regexp/text/regexp-v2/null/seqscan.sql

`&~(text, text)` specifies `STRICT`.
So, `&~ NULL` always returns `NULL`.

regexp-v2 text: add tests for NULL pattern

---

expected/regexp/varchar/regexp-v2/null/bitmapscan.out
expected/regexp/varchar/regexp-v2/null/indexscan.out
expected/regexp/varchar/regexp-v2/null/seqscan.out
sql/regexp/varchar/regexp-v2/null/bitmapscan.sql
sql/regexp/varchar/regexp-v2/null/indexscan.sql
sql/regexp/varchar/regexp-v2/null/seqscan.sql

`&~(varchar, text)` specifies `STRICT`.
So, `&~ NULL` always returns `NULL`.

regexp-v2 varchar: add tests for NULL pattern

---

src/pgroonga.c

GitHub: GH-599
Tests for this case are the following directories.
* sql/regexp/varchar/regexp-v2/null/
* sql/regexp/varchar/regexp-v2/empty/

regexp-v2 varchar: check NULL and empty as faster as possible with sequential search

---

src/pgroonga.c

GitHub: GH-599
Tests for this case exist in the following directories:
* sql/regexp/text/regexp-v2/null/
* sql/regexp/text/regexp-v2/empty/

regexp-v2 text: check NULL and empty as faster as possible with sequential search

---

src/pgrn-compatible.h
src/pgrn-options.c

We can always use `LOCKMODE` for options.

pgrn-compatible: remove PGRN_SUPPORT_OPTION_LOCK_MODE

---

src/pgrn-compatible.h
src/pgroonga.c

GitHub: GH-607
We can always use `commands/vaccum.h` and also use am parallel vacuum option for index am route.

pgrn-compatible: remove PGRN_INDEX_AM_ROUTINE_HAVE_AM_PARALLEL_VACUUM_OPTIONS

---

data/pgroonga.sql

GitHub: GH-607
So we can always use `flushed_lsn` column in pg_stat_wal_receiver table for pgroonga_list_lagged_indexes() definition.

data: use flushed_lsn column for pgroonga_list_lagged_indexes()

---

packages/apt/test.sh

GitHub: GH-607
We no longer need any prior preparation for testing packages.

package apt test: drop support for under PostgreSQL 12

---

expected/function/query-expand/multiple-terms.out
expected/function/query-expand/text.out
sql/function/query-expand/multiple-terms.sql
sql/function/query-expand/text.sql

GitHub: GH-607
So we don't have to consider the following case to use PostgreSQL 12.
- ref: https://github.com/pgroonga/pgroonga/commit/b5bba12cbbb3dbcbb3d5f2c50e434b48a43880b1

 test query-expand: drop support for PostgreSQL 12

---

packages/yum/test.sh

GitHub: GH-607
We no longer need any prior preparation for testing packages.

package yum test: drop support for under PostgreSQL 12 in AlmaLinux

---

.github/workflows/linux.yml

GitHub: GH-607
We no longer need any prior preparation for regression tests.

ci linux: drop support for PostgreSQL 12

---

.github/workflows/macos.yml

GitHub: GH-607
We no longer need any prior preparation for regression tests.

ci macos: drop support for PostgreSQL 12

---

.github/workflows/windows.yml

GitHub: GH-607
We no longer need any prior preparation for regression tests.

ci windows: drop support for PostgreSQL 12

---

.github/workflows/macos.yml

Because the current groonga formula uses Groonga 14.1.0.
- https://formulae.brew.sh/formula/groonga

ci macos: remove needless processes for old Groonga

---

.github/workflows/linux.yml
.github/workflows/macos.yml
.github/workflows/setup.yml
.github/workflows/windows.yml

We can omit `branches: "*"` to run CI for all PRs.

ci: remove redundant configurations

---

src/pgroonga-crash-safer.c
test/test-pgroonga-crash-safer.rb

GitHub: fix GH-643
`pgroonga_wal_set_applied_position()` was being called without a
schema name. If PGroonga was installed into a non-public schema,
the crash-safer background worker could not find
`pgroonga_wal_set_applied_position()` and raised an error.
In `pgroonga_crash_safer_reset_position_one()`, the code executed
"SELECT pgroonga_wal_set_applied_position()" directly using
SPI_execute(). This relies on the search path including the correct
schema for the function. If PGroonga is installed into a custom
schema, the function call fails with "does not exist" because
search path does not include that schema.
Look up the actual schema of `pgroonga_wal_set_applied_position()`
from `pg_proc` and `pg_namespace`, and then we explicitly
call it with custom schema in which PGroonga extension …

pgroonga-crash-safer: specify namespace explicitly when calling `pgroonga_wal_set_applied_position()`

---

.github/workflows/package.yml
.github/workflows/release.yml

GitHub: close GH-649
This PR is a part of automatically releasing signed packages.

ci release: create GitHub Release page and upload packages at once

---

data/pgroonga--3.2.5--4.0.0.sql
data/pgroonga--4.0.0--3.2.5.sql
data/pgroonga.sql

GitHub: GH-647
This is part of the task of remove "pgroonga" schema. It's deprecated since PGroonga 2.
This is incompatible with PGroonga 3.x or earlier.
PGroonga's test don't remove in this PR.
Because `pgroonga.bool_ops` is not used in PGroonga's tests as below.
```
% grep -r "pgroonga\.bool_ops" ./*
./data/pgroonga--3.2.5.sql:		CREATE OPERATOR CLASS pgroonga.bool_ops FOR TYPE bool
./data/pgroonga--4.0.0--3.2.5.sql:CREATE OPERATOR CLASS pgroonga.bool_ops FOR TYPE bool
./data/pgroonga--3.2.5--4.0.0.sql:DROP OPERATOR FAMILY pgroonga.bool_ops USING pgroonga;
```
---
Result of upgrade test:
```
+ sudo dnf install -y /host/almalinux/9/x86_64/Packages/postgresql17-pgdg-pgroonga-4.0.0-1.el9.x86_64.rpm
Last metadata expiration check: 0:00:19 ago on Mon Feb  3 03:26:20 2025.
Dependencies …
```

pgroonga: remove pgroonga.bool_ops operator class

---

data/pgroonga--3.2.5--4.0.0.sql
data/pgroonga--4.0.0--3.2.5.sql
data/pgroonga.sql

GitHub: GH-647
This is part of the task of remove "pgroonga" schema. It's deprecated since PGroonga 2.
This is incompatible with PGroonga 3.x or earlier.
PGroonga's test don't remove in this PR.
Because `pgroonga.int2_ops` is not used in PGroonga's tests as below.
```
% grep -r "pgroonga\.int2_ops" ./*
./data/pgroonga--3.2.5.sql:		CREATE OPERATOR CLASS pgroonga.int2_ops FOR TYPE int2
./data/pgroonga--4.0.0--3.2.5.sql:CREATE OPERATOR CLASS pgroonga.int2_ops FOR TYPE int2
./data/pgroonga--3.2.5--4.0.0.sql:DROP OPERATOR FAMILY pgroonga.int2_ops USING pgroonga;
```
---
Result of upgrade test:
```
+ sudo dnf install -y /host/almalinux/9/x86_64/Packages/postgresql17-pgdg-pgroonga-4.0.0-1.el9.x86_64.rpm
Last metadata expiration check: 0:00:22 ago on Mon Feb  3 07:36:37 2025.
Dependencies …
```

pgroonga: remove pgroonga.int2_ops operator class

---

expected/term-search/varchar-array/compatibility/v1/contain-v2/bitmapscan.out
expected/term-search/varchar-array/compatibility/v1/contain-v2/indexscan.out
expected/term-search/varchar-array/compatibility/v1/contain-v2/seqscan.out
expected/term-search/varchar-array/contain-v1/bitmapscan.out
expected/term-search/varchar-array/contain-v1/indexscan.out
sql/term-search/varchar-array/compatibility/v1/contain-v2/bitmapscan.sql
sql/term-search/varchar-array/compatibility/v1/contain-v2/indexscan.sql
sql/term-search/varchar-array/compatibility/v1/contain-v2/seqscan.sql
sql/term-search/varchar-array/contain-v1/bitmapscan.sql
sql/term-search/varchar-array/contain-v1/indexscan.sql

I removed these tests in GH-657.
However, this is mistake.
These tests for "pgroonga_varchar_array_ops" not "pgroonga.varchar_array_ops".

test: add tests for "pgroonga_varchar_array_ops" again

---

data/pgroonga--3.2.5--4.0.0.sql
data/pgroonga--4.0.0--3.2.5.sql
data/pgroonga.sql

GitHub: GH-647
This is part of the task of remove "pgroonga" schema. It's deprecated since PGroonga 2.
This is incompatible with PGroonga 3.x or earlier.
PGroonga's test don't remove in this PR.
Because `pgroonga.int8_ops` is not used in PGroonga's tests as below.
```
% grep -r "pgroonga\.int8_ops" ./*
./data/pgroonga--3.2.5.sql:		CREATE OPERATOR CLASS pgroonga.int8_ops FOR TYPE int8
./data/pgroonga--4.0.0--3.2.5.sql:CREATE OPERATOR CLASS pgroonga.int8_ops FOR TYPE int8
./data/pgroonga--3.2.5--4.0.0.sql:DROP OPERATOR FAMILY pgroonga.int8_ops USING pgroonga;
```
---
Result of upgrade test:
```
+ sudo dnf install -y /host/almalinux/9/x86_64/Packages/postgresql17-pgdg-pgroonga-4.0.0-1.el9.x86_64.rpm
Last metadata expiration check: 0:01:26 ago on Mon Feb  3 07:58:16 2025.
Dependencies …
```

pgroonga: remove pgroonga.int8_ops operator class

---

data/pgroonga--3.2.5--4.0.0.sql
data/pgroonga--4.0.0--3.2.5.sql
data/pgroonga.sql

GitHub: GH-647
This is part of the task of remove "pgroonga" schema. It's deprecated since PGroonga 2.
This is incompatible with PGroonga 3.x or earlier.
PGroonga's test don't remove in this PR.
Because `pgroonga.float4_ops` is not used in PGroonga's tests as below.
```
% grep -r "pgroonga\.float4_ops" ./*
./data/pgroonga--3.2.5.sql:		CREATE OPERATOR CLASS pgroonga.float4_ops FOR TYPE float4
./data/pgroonga--4.0.0--3.2.5.sql:CREATE OPERATOR CLASS pgroonga.float4_ops FOR TYPE float4
./data/pgroonga--3.2.5--4.0.0.sql:DROP OPERATOR FAMILY pgroonga.float4_ops USING pgroonga;
```
We can't set `pgroonga.float4_ops` now because the latest released Groonga doesn't support it. Groonga 15.0.0 will add support for `float4`.
So, PGroonga outputs the following error in downgrade test. However, this is …

pgroonga: remove pgroonga.float4_ops operator class

---

Rakefile
helper.rb

We can get the next version with `String#succ`.
```
irb(main):001:0> "4.0.0".succ
=> "4.0.1"
irb(main):002:0> "4.0.9".succ
=> "4.1.0"
```
It is no longer necessary to specify in `NEW_VERSION`.

rake: Automatically set version

---

Rakefile

When release, only `rake release` needs to be executed.

rake: Add `release` task that runs all the tasks in a release

---

data/pgroonga--3.2.5--4.0.0.sql

https://chat.zulip.org/#narrow/channel/3-backend/topic/pgroonga/near/2089150
"pgroonga.snippet_html(target text, keywords text[], width integer)" may not exist depending on the environment.
Because we forgot to define "pgroonga.snippet_html(target text, keywords text[], width integer)" in upgrade SQL( https://github.com/pgroonga/pgroonga/blob/main/data/pgroonga--2.4.1--2.4.2.sql ) when we released PGroonga 2.4.2.
So, PGroonga may occur an error when we upgrade to PGroonga 4.0.0 from PGroonga installed as 2.4.1 or earlier initially.
We can avoid this error by using "DROP FUNCTION IF EXISTS" instead of "DROP FUNCTION" as below:
Here is the log when we upgrade to 4.0.0 from 2.4.1:
```
+ sudo -u postgres -H psql --echo-all -d pgroonga_test --command 'ALTER EXTENSION pgroonga UPDATE;'
ALTER …
```

pgroonga: ensure dropping all pgroonga.snippet_html() definitions

---

.github/workflows/package.yml

It is easier to see the logs if there is no progress log.
```
$ incus --help | grep quiet
-q, --quiet          Don't show progress information
```

ci: Add `--quiet` option to `incus launch`

---

.github/workflows/package.yml

Permission error:
```
mkdir: cannot create directory ‘/host-rw/logs’: Permission denied
```
Adding the `shift=true` option solves this.
shift:
Sets up a shifting overlay to translate the source UID/GID to match the instance (only for containers)
https://linuxcontainers.org/incus/docs/main/reference/devices_disk/

ci: Add `shift=true` option to `incus config device add`

---

.github/ISSUE_TEMPLATE/bug_report.yml

For example, we can show the libgroonga version as below.
We suggest use `pgroonga_command('status')` to confirm libgroonga version.
Because `pgroonga_command('status')` returns libgroonga version surely.
We can also use `SHOW pgroonga.libgroonga_version;` to confirm libgroonga version.
However, if we use `SHOW pgroonga.libgroonga_version;`, this command is failure when we execute this command at first since we connect database.
```sql
SELECT pgroonga_command('status')::jsonb->1->'version' AS libgroonga_version;
libgroonga_version 
--------------------
"15.0.3"
(1 row)
```
For example, we can show the version of pgroonga extension as below.
```sql
SELECT extversion FROM pg_catalog.pg_extension WHERE extname = 'pgroonga';
extversion 
------------
4.0.1
(1 row)
```

issue: add SQLs for confirming version of pgroonga extension and libgroonga

---

.github/workflows/windows.yml

CMake in CI environment fails with 4.0.0.
```
CMake Error at D:/a/pgroonga/build/_deps/zstd-src/build/cmake/CMakeLists.txt:10 (cmake_minimum_required):
Compatibility with CMake < 3.5 has been removed from CMake.
Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
to tell CMake that the project requires at least <min> but has been updated
to work with policies introduced by <max> or earlier.
Or, add -DCMAKE_POLICY_VERSION_MINIMUM=3.5 to try configuring anyway.
-- Configuring incomplete, errors occurred!
```
We plan to migrate to Meson in the future.

ci: windows: Add `-DCMAKE_POLICY_VERSION_MINIMUM=3.5` option to CMake

---

.github/workflows/package.yml

With the latest GitHub Actions image, we get the following error:
```
Error: Failed to start device "host-rw": Required idmapping abilities not available
```
Same issue as this one:
https://discuss.linuxcontainers.org/t/error-failed-to-setup-device-mount-idmapping-abilities-are-required-but-arent-supported-on-system/19976
If the `shift=true` option is removed, this error will not occur.
However, when that option is removed, the GH-721 issue reoccurs.
That permission error could be avoided by creating the directory with mode=777.
So, remove the `shift=true` option and create the directory with mode=777.

ci: Fix incus device add error

---

.github/workflows/windows.yml

Related: GitHub GH-726
Already taken care of on Groonga.

ci: Remove CMAKE_POLICY_VERSION_MINIMUM=3.5

---

packages/postgresql-13-pgdg-pgroonga/yum/almalinux-8/Dockerfile
packages/postgresql-14-pgdg-pgroonga/yum/almalinux-8/Dockerfile
packages/postgresql-15-pgdg-pgroonga/yum/almalinux-8/Dockerfile
packages/postgresql-15-pgdg-pgroonga/yum/almalinux-9/Dockerfile
packages/postgresql-16-pgdg-pgroonga/yum/almalinux-8/Dockerfile
packages/postgresql-16-pgdg-pgroonga/yum/almalinux-9/Dockerfile
packages/postgresql-17-pgdg-pgroonga/yum/almalinux-8/Dockerfile
packages/postgresql-17-pgdg-pgroonga/yum/almalinux-9/Dockerfile
packages/yum/test.sh

The following error in build step is raised because Groonga APT repository doesn't serve arrow-devel-x.x.x package.
```
69.33 Error:
69.33  Problem: cannot install the best candidate for the job
69.33   - nothing provides arrow-devel >= 20.0.0 needed by groonga-devel-15.0.9-1.el8.x86_64 from groonga-almalinux
69.33 (try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```
We added/updated the official Apache Arrow repository.

ci package almalinux8/9: add/update Apache Arrow repository

---

expected/custom-scan/debug.out
sql/custom-scan/debug.sql
src/pgrn-custom-scan.c

Set up the necessary information for scanning.
* scan.scanrelid
* ID of the table to be scanned
* scan.plan.targetlist
* Information about the tuple to be returned (e.g., column information)
* scan.plan.qual
* Information on conditions such as `WHERE` clauses
Adding these will also increase the information displayed in `EXPLAIN`. We have also updated the test to check this.

custom-scan: Add information to plan

---

expected/custom-scan/debug.out
src/pgrn-custom-scan.c

The first goal is to get the results of the following query as expected.
```sql
/* sql/custom-scan/debug.sql */
SELECT content
FROM memos
WHERE content &@~ 'PGroonga OR Groonga';
```
This commit does not consider the conditions of the `WHERE` clause and fetches all data from Groonga's sources table.
The goal of the next PR is to filter by the conditions of the `WHERE` clause.

custom-scan: Fetch and return data from Groonga resources

---

meson.build

GitHub: GH-490
We added pgroonga_wal_applier module to the Meson build system like pgroonga_check did.
This module provides WAL application background worker functionality for PGroonga.

build: add Meson support for pgroonga_wal_applier module

---

meson.build

We added pgroonga-standby-maintainer module to the meson build system like other modules did.
This module provides standby server maintenance
functionality.

build: add Meson support for pgroonga_standby_maintainer module

---

src/pgrn-custom-scan.c

explain_format.* has been added and the relevant code has been moved.
https://github.com/postgres/postgres/commit/9173e8b604636633a8e3aca54bb56a437bffa718

custom-scan: Include `commands/explain_format.h` for PostgreSQL 18 or higher

---

src/pgrn-compatible.h
src/pgrn-query-expand.c

Arguments have changed since PostgreSQL 18.
https://github.com/postgres/postgres/commit/0fbceae841cb5a31b13d3f284ac8fdd19822eceb
The added an argument is for getting scan statistics and other information.
First, we do not use that information and set the value to NULL, since the behavior will be the same as before.

Support index_beginscan for PostgreSQL 18 or higher

---

src/pgrn-compatible.h
src/pgroonga-crash-safer.c
src/pgroonga-standby-maintainer.c
src/pgroonga-wal-applier.c

`pg_attribute_noreturn()` has been changed to `pg_noreturn` in PostgreSQL18.
https://github.com/postgres/postgres/commit/3691edfab97187789b8a1cbb9dce4acf0ecd8f5a
From a maintainability standpoint, we will take the approach of defining dummies and putting #if in one place.

Support for both `pg_attribute_noreturn()` and `pg_noreturn` environments

---

packages/apt/test.sh
packages/yum/test.sh

This is useful for debugging when test-primary-maintainer.sh fails.

ci: Upload logs to artifact even when test-primary-maintainer.sh fails

---

.github/workflows/linux.yml

This is a temporary solution.
PostgreSQL 18 test is still unstable, so we are ignoring the results.
Therefore, even if the test fails, `Show diff` will not be executed.
Temporarily, if `matrix.postgresql-unreleased == 'yes'`, the log will be show.

ci: Show logs when regression tests fail

---

expected/custom-scan/debug.out
src/pgrn-custom-scan.c
src/pgrn-search.h
src/pgroonga.c
src/pgroonga.h

The first goal is to get the results of the following query as expected.
```sql
/* sql/custom-scan/debug.sql */
SELECT content
FROM memos
WHERE content &@~ 'PGroonga OR Groonga';
```
Use PGrnSearchBuildCondition() to filter.

custom-scan: Filter by PGroonga operator

---

.github/workflows/macos.yml
Brewfile
meson.build

GitHub: GH-490
This PR enables building PGroonga with Meson on macOS
by addressing platform-specific compilation and module
loading requirements:
- Use PostgreSQL's complete compile flags
(`--cppflags` and `--cflags_sl`) to include the system
dependencies like gettext for libintl.h
- Handle module extension differences based on
PostgreSQL version:
- PostgreSQL < 16: use .so extension
- PostgreSQL >= 16: use .dylib extension

ci macos: add Meson build support

---

src/pgrn-compatible.h
src/pgroonga.c

We can implements amtranslatecmptype and amtranslatestrategy in index access method by https://github.com/postgres/postgres/commit/a8025f544854ad8b865c6b4509030ee84aa8f4a0.
If we don't implement them explicitly, PostgreSQL doesn't be regarded as ordered index.
PGroonga can return ordered result. So, we need to implement amtranslatecmptype and amtranslatestrategy.

Add support for amtranslate routines for PostgreSQL 18 or higher

---

.github/workflows/package.yml
packages/postgresql-14-pgdg-pgroonga/Rakefile
packages/postgresql-14-pgdg-pgroonga/apt/debian-trixie-arm64/from
packages/postgresql-14-pgdg-pgroonga/apt/debian-trixie/Dockerfile
packages/postgresql-14-pgdg-pgroonga/debian/rules

This commit is part of the work to implement GH-779.
The package name of MessagePack change to msgpack-c from msgpack since Debian 13 (trixie).

packages postgresql-14: add support for Debian 13

---

src/pgrn-pg.c

`fmNodePtr` was removed:
https://github.com/postgres/postgres/commit/4bd91912987d794c48dd4ba4c337906bd23759be
https://github.com/pgroonga/pgroonga/actions/runs/17998815903/job/51203377015#step:8:43
```text
In file included from ../pgroonga/src/pgroonga.h:9,
from ../pgroonga/src/pgrn-pg.c:1:
../pgroonga/src/pgrn-pg.c: In function ‘PGrnPGHavePreparedTransaction’:
../pgroonga/src/pgrn-pg.c:299:65: error: ‘fmNodePtr’ undeclared (first use in this function)
299 |                         *fcinfo, &flinfo, 0, InvalidOid, NULL, (fmNodePtr) &rsinfo);
|                                                                 ^~~~~~~~~
```

postgresql-19: use `Node *' instead of `fmNodePtr`

---

.github/workflows/linux.yml
src/pgroonga-crash-safer.c
src/pgroonga-standby-maintainer.c

`VARDATA_ANY()`/`VARSIZE_ANY_EXHDR` were re-implemented as `static inline` functions:
https://github.com/postgres/postgres/commit/e035863c9a04beeecc254c3bfe48dab58e389e10
So we need to use `const void *` not `Datum` for their arguments. We can use `DatumGetPointer()` for it.
https://github.com/pgroonga/pgroonga/actions/runs/18021762544/job/51280586570#step:8:65
```text
../pgroonga/src/pgroonga-crash-safer.c: In function ‘pgroonga_crash_safer_reindex_one’:
../pgroonga/src/pgroonga-crash-safer.c:300:70: warning: passing argument 1 of ‘VARDATA_ANY’ makes pointer from integer without a cast [-Wint-conversion]
300 |                                 indexNames[i] = pnstrdup(VARDATA_ANY(indexName),
|                                                                      ^~~~~~~~~
| …
```

postgresql-19: cast `Datum` to `Pointer` for `VARDATA_ANY()`/`VARSIZE_ANY_EXHDR`

---

.editorconfig
.github/workflows/linux.yml
expected/regexp/text-array/regexp-v2/null/bitmapscan.out
expected/regexp/text-array/regexp-v2/null/bitmapscan_1.out
expected/regexp/text-array/regexp-v2/null/indexscan_1.out
expected/regexp/text-array/regexp-v2/null/seqscan.out
expected/regexp/text-array/regexp-v2/null/seqscan_1.out
expected/regexp/text/regexp-in/null/bitmapscan.out
expected/regexp/text/regexp-in/null/bitmapscan_1.out
expected/regexp/text/regexp-in/null/indexscan_1.out
expected/regexp/text/regexp-in/null/seqscan_1.out
expected/regexp/text/regexp-v2/null/bitmapscan_1.out
expected/regexp/text/regexp-v2/null/indexscan.out
expected/regexp/text/regexp-v2/null/indexscan_1.out
expected/regexp/text/regexp-v2/null/seqscan.out
expected/regexp/text/regexp-v2/null/seqscan_1.out
expected/regexp/varchar/regexp-in/null/bitmapscan.out
expected/regexp/varchar/regexp-in/null/bitmapscan_1.out
expected/regexp/varchar/regexp-in/null/indexscan.out
expected/regexp/varchar/regexp-in/null/indexscan_1.out
expected/regexp/varchar/regexp-in/null/seqscan.out
expected/regexp/varchar/regexp-in/null/seqscan_1.out
expected/regexp/varchar/regexp-v2/null/bitmapscan.out
expected/regexp/varchar/regexp-v2/null/bitmapscan_1.out
expected/regexp/varchar/regexp-v2/null/indexscan_1.out
expected/regexp/varchar/regexp-v2/null/seqscan.out
expected/regexp/varchar/regexp-v2/null/seqscan_1.out

It's added by:
https://github.com/postgres/postgres/commit/f2bae51dfd5b2edc460c86071c577a45a1acbfd7
We can remove `_1.out` files when we drop support PostgreSQL 18.

test postgresql-19: add support for "Replaces" in EXPLAIN result

---

expected/function/score/hot/custom-scan/with-id.out
expected/function/score/hot/custom-scan/without-id.out
sql/function/score/hot/custom-scan/with-id.sql
sql/function/score/hot/custom-scan/without-id.sql
src/pgrn-compatible.h
src/pgrn-custom-scan.c

It didn't work on a table with multiple columns, so we changed it to work.
The test for `sql/function/score/hot/custom-scan/*` had an incorrect parameter name and was not testing the custom scan.

custom-scan: Support multiple columns

---

expected/custom-scan/no-index.out
sql/custom-scan/no-index.sql
src/pgrn-custom-scan.c

Even when custom scan is enabled, it is meaningless without an index, so it is not added to the plan path.

custom-scan: Not add to the plan path when there is no PGroonga index

---

expected/full-text-search/varchar/query-v2/partitioning/many-partition.out
sql/full-text-search/varchar/query-v2/partitioning/many-partition.sql

Specify `pgroonga_varchar_full_text_search_ops_v2` so that `&@~` can be used.

varchar/query-v2: Fix many-partition test

---

.github/workflows/release.yml

Fix: GH-818,
"actions/checkout" removing the contents of '/home/runner/work/pgroonga/pgroonga'. 
So, if we execute "actions/checkout" after downloading artifacts, "actions/checkout" remove "release-artifacts" directory.

ci release: move checkout repository before downloading artifacts

---

expected/full-text-search/varchar/query-v2/partitioning/many-partition_1.out
sql/full-text-search/varchar/query-v2/partitioning/many-partition.sql

_1.out is for PostgreSQL < 18.
PostgreSQL < 18 doesn't show `Disabled: true`.

test: force using index for stable result

---

expected/custom-scan/unsupported-operator.out
sql/custom-scan/unsupported-operator.sql
src/pgrn-custom-scan.c

For unsupported operators, a standard scan will be executed.

custom-scan: No custom scan for unsupported operators

---

expected/compare/float4/single/any/equal/multiple/custom-scan.out
sql/compare/float4/single/any/equal/multiple/custom-scan.sql
src/pgrn-compatible.h
src/pgrn-custom-scan.c

By setting `cpath->path.pathkeys`, we inform the planner that the custom scan results are sorted.
`pathkeys` is not included in `CustomScanState`, so we use `custom_private` to pass them.

custom-scan: Support sorting by index

---

src/pgrn-custom-scan.c

* Unify the argument name of CustomScanState to customScanState.
* Create a function that sets ResultTupleSlot in ExecCustomScan.
* There are no changes to the logic.
* This is preparation for changing ExecCustomScan later.
* Add initialization of state->ctidAccessor.
* This is more of an addition to fix an omission rather than refactoring.

custom-scan: Refactoring
