.github/workflows/package.yml
Rakefile
packages/postgresql-14-pgdg-pgroonga/apt/ubuntu-jammy-arm64/from
packages/postgresql-14-pgdg-pgroonga/apt/ubuntu-jammy/Dockerfile
packages/postgresql-14-pgroonga/debian/changelog

package: add support for Ubuntu 22.04 (Jammy Jellyfish)

---

expected/full-text-search/varchar/query-v2/partitioning/many-partition.out
sql/full-text-search/varchar/query-v2/partitioning/many-partition.sql

This test for confirming a modification of https://github.com/pgroonga/pgroonga/commit/b54cd0ce34d13e2c0a9a473b6631c0efcaf40265.
The version 2.3.8 or less of PGroonga crashed in this test case.

test: add a test for existing many partition tables

---

.github/workflows/windows.yml

GitHub: Fix #256.
Reported by Raif Atef. Thanks!!!

ci windows: add PostgreSQL 15

---

.github/workflows/linux.yml
.github/workflows/macos.yml

Adding the parameters will cause the test to pass. 
https://github.com/pgroonga/pgroonga/discussions/406#discussioncomment-8550910

ci: Enable the test that was disabled

---

.github/workflows/macos.yml

Reference:
https://github.com/groonga/groonga/commit/8275463f7d8f8fc7308b232049fdb0cf538bd3d5

ci macos: add workaround for msgpack-c

---

Rakefile

Example: Downgrade from 3.2.2 to 3.2.1.
* data/pgroonga--3.2.2--3.2.1.sql
* data/pgroonga_database--3.2.2--3.2.1.sql
`ALTER EXTENSION pgroonga UPDATE ` will be successful in downgraded.

Add SQL files for downgrade

---

data/pgroonga--3.2.0--3.2.1.sql
data/pgroonga--3.2.1--3.2.0.sql
data/pgroonga.sql
expected/function/list-broken-indexes/nothing.out
makefiles/pgroonga-sources.mk
sql/function/list-broken-indexes/nothing.sql
src/pgrn-list-broken-indexes.c

Prepare to implement a function that lists the indexes of PGroonga's that may be broken.

Add pgroonga_list_broken_indexes() skeleton

---

src/pgrn-jsonb.c

If it failed, PGroonga crashes, so it is checked by PGrnCheck().

Check with PGrnCheck() after `grn_expr_append_*` at PGrnJSONBMatchExpression()

---

src/pgrn-jsonb.c

If it failed, PGroonga crashes, so it is checked by PGrnCheck().

Check with PGrnCheck() after `grn_expr_append_*` at PGrnSearchBuildConditionJSONScript()

---

data/pgroonga--3.2.0--3.2.1.sql
data/pgroonga.sql
src/pgrn-wal.c
test/test-streaming-replication.rb

* List PGroonga indexes with unapplied WAL in pgroonga_wal_status()
* List all PGroonga indexes if primary log position and lag

Check the lag with pgroonga_wal_status()

---

src/pgrn-groonga.c
src/pgrn-groonga.h

Check with PGrnCheck() after grn_expr_append_op().

Add PGrnExprAppendOp()

---

src/pgrn-list-broken-indexes.c

Refactoring:
Implemented a function for common checks.

list-broken-indexes: Add PGrnIsBrokenGrnObj()

---

src/pgrn-jsonb.c

Changed the value of the log tag to include `jsonb` in PGrnExprAppendOp() tag as well.

Use PGrnExprAppendOp() instead of grn_expr_append_op() in pgrn-jsonb.c

---

src/pgrn-groonga.c
src/pgrn-groonga.h

Check with PGrnCheck() after grn_expr_append_const_str().

Add PGrnExprAppendConstString()

---

src/pgrn-groonga.c
src/pgrn-groonga.h

Check with PGrnCheck() after grn_expr_append_const().

Add PGrnExprAppendConst()

---

src/pgrn-groonga.c
src/pgrn-groonga.h

Check with PGrnCheck() after grn_expr_append_obj().

Add PGrnExprAppendObject()

---

src/pgroonga.c

Replaced only where there is no PGrnCheck().

Use PGrnExprAppendObject() instead of grn_expr_append_obj()

---

src/pgroonga-primary-maintainer.c
test/test-streaming-replication.rb

Only the looping part.
The main processing is implemented in the next PR.

pgroonga-primary-maintainer: Implement a process to be run periodically

---

src/pgroonga-primary-maintainer.c
test/test-streaming-replication.rb

The implementation of the main process, such as the WAL size check, is the next commit.

pgroonga-primary-maintainer: Process each database

---

packages/pgroonga/yum/pgroonga.spec.in
packages/yum/postgresql-pgroonga.spec.in
pgroonga.mk
test/test-tools-service-file-generator.rb

pgroonga-generate-primary-maintainer-service: Add the service file generator to the installation target

---

.github/workflows/package.yml

ci package: prepare Incus to execute tests on it instead of Docker

---

packages/test-systemd-timer.sh

Run in a test script such as `packages/yum/test.sh`.

packages: Add a script to test systemd timer

---

.github/workflows/package.yml
packages/apt/test.sh

ci package: migrate test environment from Docker to Incus base

---

.github/workflows/macos.yml

https://formulae.brew.sh/formula/msgpack
stable 6.0.2
```
% cat $(brew --prefix msgpack)/lib/pkgconfig/msgpack-c.pc
prefix=/usr/local/Cellar/msgpack/6.0.2
exec_prefix=/usr/local/Cellar/msgpack/6.0.2
libdir=${prefix}/lib
includedir=${prefix}/include
Name: MessagePack
Description: Binary-based efficient object serialization library
Version: 6.0.2
Libs: -L${libdir} -lmsgpack-c
Cflags: -I${includedir}
```

test: Remove a step that is no longer needed

---

.github/workflows/macos.yml

The issue has been fixed.
https://github.com/Homebrew/homebrew-core/issues/171137

ci: Use macos-latest

---

.github/workflows/package.yml
packages/postgresql-17-pgdg-pgroonga/Rakefile
packages/postgresql-17-pgdg-pgroonga/apt/ubuntu-focal-arm64/from
packages/postgresql-17-pgdg-pgroonga/apt/ubuntu-focal/Dockerfile

GitHub: GH-552
We add support for PostgreSQL 17 on Ubuntu focal by this PR.

packages ubuntu focal: add support for PostgreSQL 17

---

.github/workflows/package.yml
packages/apt/test.sh
packages/postgresql-17-pgdg-pgroonga/Rakefile
packages/postgresql-17-pgdg-pgroonga/yum/almalinux-8/Dockerfile
packages/yum/test.sh

GitHub: GH-552
We add support for PostgreSQL 17 on AlmaLinux 8 by this PR.

packages almalinux-8: add support for PostgreSQL 17

---

.github/workflows/package.yml
packages/postgresql-17-pgdg-pgroonga/Rakefile
packages/postgresql-17-pgdg-pgroonga/yum/almalinux-9/Dockerfile

GitHub: GH-552
We add support for PostgreSQL 17 on AlmaLinux 9 by this PR.

packages almalinux-9: add support for PostgreSQL 17

---

.pre-commit-config.yaml
Rakefile

GitHub: fixes GH-564
Reference: https://github.com/mroonga/mroonga/commit/495ac9ecad08c2d4edd43de49cb9c5f990e7d801

ci: detect maintained/unmaintained packages list automatically

---

test/test-pgroonga-check.rb

Related: https://github.com/pgroonga/pgroonga/commit/533cec6e7a4f449ab10cd03214f09f3ab5a02449

test: Change to follow `read_command_output_all` specification changes

---

packages/apt/test.sh

This test confirm behavior of downgrade SQL under the "data/" directory.

package apt test: add a test for downgrading PGroonga version

---

packages/yum/test.sh

This test confirm behavior of downgrade SQL under the "data/" directory.

package yum test: add a test for downgrading PGroonga version

---

.github/workflows/lint.yml
.github/workflows/linux.yml
.github/workflows/macos.yml
.github/workflows/package.yml
.github/workflows/setup.yml
.github/workflows/windows.yml

We can use GitHub Actions on fork by this.

ci: enable workflows for all pushes

---

data/pgroonga--3.2.4--3.2.5.sql
data/pgroonga--3.2.5--3.2.4.sql
data/pgroonga.sql

GitHub: GH-615
Fix the offset condition because the previous condition always returned true.

pgroonga_list_lagged_indexes(): fix the offset condtion

---

.github/workflows/package.yml

QEMU is slow and may occur segmentation falt.

ci package: use ubuntu-24.04-arm for arm64 packages 

---

.github/workflows/package.yml
.github/workflows/windows.yml

GitHub: GH-649
This PR is a part of automatically releasing signed packages.
- Using release event triggers the webhook

ci release package: group by distribution+version

---

expected/custom-scan/debug.out
sql/custom-scan/debug.sql
src/pgrn-custom-scan.c
src/pgrn-custom-scan.h
src/pgroonga.c

Prepare to implement custom scan.
https://www.postgresql.org/docs/current/custom-scan.html

Add skeletons to implement custom scan

---

src/pgroonga.c
src/pgroonga.h

Because we want to use it for custom scan as well.

Expose PGrnConvertToDatum()

---

.github/workflows/linux.yml
meson.build
meson_options.txt

GitHub: GH-490
We added pgroonga module to the meson build system like other modules did.
We will add simple tests. In the following PR, we will add full test step.

build: add Meson support for pgroonga module

---

src/pgrn-custom-scan.c

It is better to use TupleDescAttr().
It is also used in PGroonga's existing code.

Use TupleDescAttr to get attr

---

src/pgrn-compatible.h
src/pgroonga.c

Member name changed.
https://github.com/postgres/postgres/commit/0fbceae841cb5a31b13d3f284ac8fdd19822eceb

Support ParallelIndexScanDesc::ps_offset_am for PostgreSQL 18 or higher

---

src/pgroonga.c

Related commit:
https://github.com/postgres/postgres/commit/92fe23d93aa3bbbc40fca669cabc4a4d7975e327
`Relation indexRelation` argument has been added.

amestimateparallelscan_function: Follow PostgreSQL 18 definition

---

.github/workflows/linux.yml
.github/workflows/macos.yml
.github/workflows/windows.yml

It's released:
https://www.postgresql.org/about/news/postgresql-18-released-3142/

ci: add PostgreSQL 18

---

expected/full-text-search/text/single/match-condition-v2/fuzzy-max-distance-ratio/little-fuzzy/custom-scan.out
expected/full-text-search/text/single/match-condition-v2/fuzzy-max-distance-ratio/very-fuzzy/custom-scan.out
sql/full-text-search/text/single/match-condition-v2/fuzzy-max-distance-ratio/little-fuzzy/custom-scan.sql
sql/full-text-search/text/single/match-condition-v2/fuzzy-max-distance-ratio/very-fuzzy/custom-scan.sql
src/pgrn-custom-scan.c

custom-scan: support `fuzzy_max_distance_ratio` option for pgroonga_condition()

---

expected/full-text-search/jsonb/match-v2/custom-scan.out
expected/full-text-search/jsonb/match-v2/row-level-security/custom-scan.out
sql/full-text-search/jsonb/match-v2/custom-scan.sql
sql/full-text-search/jsonb/match-v2/row-level-security/custom-scan.sql
src/pgrn-custom-scan.c

When handling JSONB, fetch the data from the table.
We checked it first with the `sql/full-text-search/jsonb/match-v2` test.
We'll check with the other tests next.

custom-scan: Support JSONB
